title: Technical Writing Portfolio
description: Portfolio of technical writing samples by G.K. Fen
theme: minima

url: https://gorbsworld.github.io
baseurl: /gkf-portfolio

header_pages:
  - index.md
