title: Technical Writing Portfolio
description: Portfolio of technical writing samples by G. K. Fennell
theme: minima

minima:
skin: dark

url: https://gorbsworld.github.io
baseurl: /gkf-portfolio

header_pages:
  - index.md
